# Generated by Django 3.1 on 2021-09-23 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text=' Nome da categoria dos produtos ', max_length=100, unique=True)),
                ('slug', models.SlugField(help_text='Slug do nome do produtos ', max_length=100, unique=True)),
            ],
            options={
                'ordering': ('-name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome do Produto', max_length=150, unique=True)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('image', models.ImageField(help_text='image do Produto', upload_to='products')),
                ('description', models.TextField(help_text='Descrição do Produto')),
                ('shu', models.CharField(max_length=40)),
                ('price', models.DecimalField(decimal_places=2, help_text='O Valor do Produto', max_digits=10)),
                ('available', models.BooleanField(default=True)),
                ('category', models.ForeignKey(help_text='categoria do produto', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='produtos.category')),
            ],
            options={
                'ordering': ('shu',),
            },
        ),
    ]
